### ISSUE TITLE
The `--set-metadata` option does not overwrite/set metadata anymore

### ISSUE THREAD

**Issue by FritsHoogland** [cat-in-136/cargo-generate-rpm#118]
cargo generate-rpm version 0.15.1

Cargo.toml:
```
[package.metadata.generate-rpm]
assets = [
    { source = "target/release/procstat", dest = "/usr/local/bin/procstat", mode = "0755" },
]
release = "1.el8"
```

command:
```
cargo generate-rpm --set-metadata='release = '1.el9'"
```

Results :
```
target/generate-rpm/procstat-0.1.33-1.el8.aarch64.rpm
```
This works with version 0.14.1.

**Comment by cat-in-136** [comment]
I have successfully reproduced.

- release build works fine: `target/release/cargo-generate-rpm generate-rpm` works without any error. 
- debug build fails (even if there is no option): `target/debug/cargo-generate-rpm generate-rpm` raises a panic: `"metadata_overwrite"` is not an id of an argument or a group.

**Comment by cat-in-136** [comment]
@FritsHoogland  Thank you very much for clarification.

I have checked with various combinations. I found that `--set-metadata` (or `-s`) are not referenced when run as a cargo subcommand like `cargo generate-rpm` instead of `cargo-generate-rpm`. In addition, the debug build does not work at all in this condition. Anyway, both should be fixed and probably have the same cause.

| build   | Cargo.toml release | --set-metadata | subcommand?  | Actual result  | Note                                                                               |
| ------- | ------------------ | -------------- | ------------ | -------------- | ---------------------------------------------------------------------------------- |
| debug   |                    |                |              | PASS           | Release=1                                                                          |
| debug   |                    |                | generate-rpm | FAIL(panicked) | `"metadata_overwrite"` is not an id of an argument or a group. |
| debug   |                    | 1.el9          |              | PASS           | Release=1.el9                                                                      |
| debug   |                    | 1.el9          | generate-rpm | FAIL(panicked) | `"metadata_overwrite"` is not an id of an argument or a group. |
| debug   | 1.el8              |                |              | PASS           | Release=1.el8                                                                      |
| debug   | 1.el8              |                | generate-rpm | FAIL(panicked) | `"metadata_overwrite"` is not an id of an argument or a group. |
| debug   | 1.el8              | 1.el9          |              | PASS           | Release=1.el9                                                                      |
| debug   | 1.el8              | 1.el9          | generate-rpm | FAIL(panicked) | `"metadata_overwrite"` is not an id of an argument or a group. |
| release |                    |                |              | PASS           | Release=1                                                                          |
| release |                    |                | generate-rpm | PASS           | Release=1                                                                          |
| release |                    | 1.el9          |              | PASS           | Release=1.el9                                                                      |
| release |                    | 1.el9          | generate-rpm | FAIL           | Release=1                                                                          |
| release | 1.el8              |                |              | PASS           | Release=1.el8                                                                      |
| release | 1.el8              |                | generate-rpm | PASS           | Release=1.el8                                                                      |
| release | 1.el8              | 1.el9          |              | PASS           | Release=1.el9                                                                      |
| release | 1.el8              | 1.el9          | generate-rpm | FAIL           | Release=1.el8                                                                      |

* In this table, empty cell indicates not specifying the parameter

**Comment by FritsHoogland** [comment]
Currently, I have set cargo generate-rpm back to installing version 0.14.1 in my build pipelines, and that works okay.
