### ISSUE TITLE
Using multi-line scripts

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#17]
Hi,

The README.md says:

> pre_install_script: optional string of pre_install_script.
> pre_uninstall_script: optional string of pre_uninstall_script.
> post_install_script: optional string of post_install_script.
> post_uninstall_script: optional string of post_uninstall_script.

How could I instead execute entire scripts instead of single commands?

The context for this question is an RPM that needs to install systemd services and create user accounts etc.

I "hacked' around this limitation in a test by including the scripts as assets with a `/tmp` destination and then used the "xxx_script" hooks to execute the script from `/tmp/`. However, the script then also needs to take care of removing itself which is a bit ugly.

Any suggestions welcome.

Thanks,

Ximon

**Comment by ximon18** [comment]
Thanks.

And if I want the script to be a file outside of Cargo.toml? I'd rather not put lots of Bash script into my Cargo.toml.

Ximon

**Comment by cat-in-136** [comment]
Like RPM native spec file format, scriptlets shall be written Cargo.toml directly. It is not really intended to be huge scripts with more than hundred lines long.

IMHO, considering the transparency for users, it is better to leave the large script stored in a separated file such as /usr/share/foobar/rpm/install-script.sh so that they can refer to it later.

**Comment by ximon18** [comment]
Thanks for the advice. I do not want scriptlets in Cargo.toml, I don't want it to become cluttered and to mix purposes and languages together like that. However I hadn't thought about using assets under `/usr/share`, I will try that as indeed it is good if the scripts invoked are available on the host post (successful or failed) install.

**Comment by ximon18** [comment]
So we realized that the workaround of specifying a command that runs a script file doesn't work for `post_uninstall_script` as by the time it is run the script has been removed from disk.

Still not wanting to pollute my `Cargo.toml` with Bash scripts I'm now trying to see if the new `--set-metadata` functionality can help here, with:

```
cargo generate-rpm --set-metadata "post_uninstall_script = \"\"\"$(cat pkg/rpm/postuninst)\"\"\""
```

This looks fine when the created package is inspected:

```
$ rpm -qp --scripts target/generate-rpm/routinator-0.12.0-dev-1.x86_64.rpm 
postinstall scriptlet:
/usr/share/routinator/rpm/postinst $*
preuninstall scriptlet:
/usr/share/routinator/rpm/preuninst $*
postuninstall scriptlet:
#!/bin/bash -e
# Script based on the RPM %systemd_postun scriptlet. See:
#   - https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
#   - https://cgit.freedesktop.org/systemd/systemd/tree/src/core/macros.systemd.in

systemctl daemon-reload >/dev/null 2>&1 || :
if [ $1 -ge 1 ] ; then
    systemctl try-restart routinator.service >/dev/null 2>&1 || :
fi
```

**Comment by cat-in-136** [comment]
Since it is up to an RPM specification, these scripts should be defined using a multi-string string, such as https://github.com/cat-in-136/cargo-generate-rpm/issues/17#issuecomment-848860537. Of course, you can use escaped linefeed `\n` in a basic string instead of raw string in a multi-line basic string (see also: https://toml.io/en/v1.0.0#string ).
