### ISSUE TITLE
Support custom and auto requires

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#8]
Hi,

I need to specify a require when building an RPM but, unless I missed something, to do that with this crate I have to fork the crate and invoke `requires` myself, e.g.:

```
builder = builder.requires(rpm::Dependency::eq("openssl-libs", "1:1.1.1g-12.el8_3"));
```

It occurs to me that the [cargo-deb crate](https://github.com/mmstick/cargo-deb) supports specification of Deb package dependencies in `Cargo.toml`, and has [Rust code for invoking `ldd` and `dpkg -S`](https://github.com/mmstick/cargo-deb/blob/master/src/dependencies.rs) (disclaimer: I use cargo-deb and contributed to it as well) to identify the packages the built binaries depend on and for using those if the user specifies either no dependencies or includes "$auto" in the list of dependencies.

Thus I would like a way to specify dependencies myself in the `Cargo.toml` file ala cargo-deb, and even better the `$auto` depends functionality too. For RPMs that could be done with parsing the output of `ldd` and then using `rpm -qf </path/to/lib>` to work out the package that provides the lib.

Is this of interest? Would you be open to a pull request? I could check with the author of cargo-deb if he minds code being copied from that project and modified for use here. Alternatively, and I'm dubious about the benefits of this, perhaps looking further ahead if there is sufficient commonality between this project and cargo-deb there could be a way to share code (factor out common elements to a support crate?) or combine the projects even (not sure that is wise, logic added for RPMs might have unintended consequences for DEB packaging or vice versa, automated testing would have to be quite thorough to avoid such inadvertent mistakes).

Ximon

**Comment by cat-in-136** [comment]
Thanks for your suggestion. First of all, pull requests are welcome.

I believe that the dependencies described in https://rpm.org/user_doc/dependencies.html need to be implemented. But I have not yet gained enough survey to design it.

Unlike https://github.com/iqlusioninc/cargo-rpm/issues, this project does not require the rpm/rpmbuild command and uses rpm-rs crate to create the rpm files. In addition, I think there are some technical difficulties related to RPM itself.

* There are multiple distributions that use RPMs (rhel, fedora, opensuse, etc...) but the package names are not always same among these distributions.
* The Automatic Dependency process performed by rpmbuild command is so good that there is little need to specify the requires relationship. It is necessary to implement own processing without rpm/rpmbuild as you mentioned.

**Comment by ximon18** [comment]
I’m not sure if we are understanding each other completely, or at least your answer doesn’t seem to me to comment on the suitability or otherwise of the approach I outlined.

Regarding use of rmbuild, indeed I like the lack of dependence on external tooling such as rpmbuild but for me the more important distinction between this project and cargo-rpm is the use of Cargo.toml for specifying RPM related details rather than the use of separate spec files, which is why I looked into using this crate instead of cargo-rpm.

For the case of wanting to enable RPM users to install a package containing one or more Rust binaries and to have any necessary dependencies be automatically installed as well is specifying Requires not enough?

And to avoid the pain of determining dependencies is the $auto approach (not requiring rpmbuild, though requiring ldd and rpm) not sufficient?

The equivalent approach in the cargo-deb crate doesn’t seem to have encountered any major issues hence my idea to apply it here to. In a quick test it, for my case at least, worked nicely. My RPM installed and yum fetched the openssl-libs dependency for me.

FYI for a bit of context, perhaps it helps to see where I’m approaching this from, for the DEB case I build in various different Docker containers (different versions of Ubuntu and Debian) using a GitHub Actions matrix build invoking cargo-deb and via the $auto approach specify the correct dependency for that O/S flavour. I also then test in a similar way by installing each built package in an instance of the target O/S flavour, but this time using LXC/D containers (in my case this is to get proper systemd for testing as that’s not used inside Docker containers).

If I can find time perhaps I should try and out together a PR to explore the approach, not yet a PR suitable for merging but more a proof of concept?

Ximon

**Comment by cat-in-136** [comment]
> And to avoid the effort of determining dependencies is the $auto approach (not requiring rpmbuild, though requiring ldd and rpm) also not useful?

ldd is available in the typical environment where glibc is installed. I agree it is ok to require ldd. But, I believe that requiring rpm is not a good idea for cargo-generate-rpm policy.

On the other hand, I understand the intention to automatically resolve dependencies.

I have inspected your proposal again. It found that your way is a little against RPM's auto dependency process way and there is a more preferable way. Even if I accepted your strategy and the pull request, I will treat it as an optional behavior, not a default behavior.


---

RPM require list items can be written not only as package names but also as library file names.

For example, please refer "Requires" section in [openssl-1.1.1g-15.fc33.x86\_64 RPM](https://www.rpmfind.net/linux/RPM/fedora/33/x86_64/o/openssl-1.1.1g-15.fc33.x86_64.html).

- The shell (such as /bin/sh) listed at the beginning of the  **Requires** list is implicitly.
  - It is already done on cargo-rpm-build because [rpm-rs did](https://github.com/Richterrettich/rpm-rs/blob/2dac707469cdc3a6c7032abd98d13bf494e00665/src/rpm/builder.rs#L410)
- The package name (such as `coreutils`) is explicitly written at the spec file.
- The library name (such as `libc.so.6()(64bit)`) is not written at the spec file but is listed by rpmbuild automatic dependency process, which is described at http://ftp.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html

It indicates that Require list resolved automatically should not be listed using package names.

Based on the above surveys, the default dependency-related process of cargo-generate-rpm should do as follows:

* cargo-generate-rpm shall apply dependency of shell to the RPM file (already done!)
* cargo-generate-rpm shall apply require package name dependencies written in the Cargo.toml to the RPM file (FFS Cargo.toml format).
* cargo-generate-rpm shall run ldd on all executable files, list up the dependent library files (`libXX.so.X()(64bit)`), and reflect them to the RPM file.

This way is more portable among (RPM-based) different distributions. The package are not always same among these distributions (e.g. libopenssl vs openssl). It can also be usable for running cargo-generate-rpm on environment where RPM is not installed, such as Ubuntu on GitHub Action.

**Comment by ximon18** [comment]
Thanks a lot @cat-in-136 for taking the time to think this through, as you can see I'm not RPM expert so apologies for any issues I can and perhaps should have realized with my proposal above. I'll have to re-read the details of your reply to understand it fully and read the given linked documents, but it sounds great, no need for an `rpm` binary dependency at build time and still the benefit of capturing dependencies automatically.

**Comment by cat-in-136** [comment]
After checking again, I noticed that your following mentions are very right.

>  for me the more important distinction between this project and cargo-rpm is the use of Cargo.toml for specifying RPM related details rather than the use of separate spec files

For example, *fake* rpm and rpmbuild are installed on the Ubuntu environment on Github Action, but even so, it is useful to be able to create an RPM file just from Cargo.toml useless of spec file.

Therefore, we are thinking of providing the following four modes of *auto-req*.

* call `find-requires`: Just call `/usr/lib/rpm/find-requires`, which is exactly same way as one of rpmbuild. This mode shall be used for the environment where rpmbuild is installed, including _fake_ rpm  e.g. Ubuntu on Github Action. Because `/usr/lib/rpm/find-requires` is provided by rpmbuild (not rpm).
* call `ldd` and parsing elf binaries: Obtain the requirements-list using ldd as @ximon18 suggested, but instead of looking for the (installed) RPM packages, resolving to the library name such as `libc.so.6(GLIBC_2.28)(64bit)`, .... It is also  necessary to analyze the ELF binary partially to determine if `rtld(GNU_HASH)` is added to the list.
* auto: call `find-requires` if `/usr/lib/rpm/find-requires` exists, otherwise call `ldd` and parsing elf binaries.
* disable: do not process *auto-req*

**Comment by ximon18** [comment]
As _auto-req_ requires qiute some work compared to manual specification of dependencies, would it be good to separate these two out so that manually specified dependencies can be offered as a feature without waiting for the _auto-req_ feature to be implemented, and the _auto-req_ feature may need to be overridable by manual specification anyway in some cases?

**Comment by cat-in-136** [comment]
@ximon18, the original rpmbuild is "auto-req" enabled and you can set dependencies manually. I plan to make my program like that.

I'll provide settings to disable "auto-req" in both the command line option and like of flag in Cargo.toml. The command line is for general users. The flag in Cargo.toml is for the crate author to express that auto-req is not desired for their crates, where original rpmbuild also provides as `AutoReqProv: no`.

Implementation is still on-going. I have implemented command line option `--auto-req disabled`, but have not yet implemented latter. I have not yet updated README. As of now, use `--auto-req disabled` with *dependency-support* branch code.

**Comment by ximon18** [comment]
Thanks @cat-in-136 for spending time on this. I’ll take a look at what you have changed.
