### ISSUE TITLE
error: unpacking of archive failed on file /lib/systemd/system/xxx.service;6496c577: cpio: Digest mismatch

### ISSUE THREAD

**Issue by vkill** [cat-in-136/cargo-generate-rpm#87]
Hi, there

When I run `sudo yum localinstall -y target/generate-rpm/*-0.1.0-1.x86_64.rpm`, the `Digest mismatch` error happened.

But I have no problem using 0.11.0

```
cargo install cargo-generate-rpm --version 0.11.0 --force
cargo generate-rpm --payload-compress gzip
```

**Comment by cat-in-136** [comment]
@vkill I could not reproduced. Could you please share the repository you use?

**Comment by cat-in-136** [comment]
it seems related to rpm-rs/rpm#148

**Comment by vkill** [comment]
@cat-in-136 Yes, CentOS 7

**Comment by fritshoogland-yugabyte** [comment]
the digest error is because executable in the file, at least in my case, is zero bytes.
that means that the errors you find about tips etc. are not true in this case: the file included in the rpm is zero bytes.
if I install cargo-generate-rpm 0.11.0, I get a non-zero executable, and it works.
same here too: centos 7
